CREATE TABLE IF NOT EXISTS role (
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  role varchar(20) NOT NULL
) ;

CREATE TABLE IF NOT EXISTS user (
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  login varchar(20) NOT NULL,
  password varchar(20) NOT NULL
) ;

CREATE TABLE IF NOT EXISTS user_roles (
  user_id integer NOT NULL,
  role_id integer NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user(id),
  FOREIGN KEY (role_id) REFERENCES role(id)
) ;
